version: '3'
volumes:
  node_modules_data:
    driver: local

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/codevolution
      - node_modules_data:/codevolution/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"